version: '3'

services:
  gympass-style-app:
    image: 'bitnami/postgresql:latest'
    ports: 
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=gympassapp