name: Run E2E Tests

on: [pull_request]

jobs:
  run-unit-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      gympass-style-app:
        image: bitnami/postgresql
        ports: 
          - 5434:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: gympassapp

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9.5.0  

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

      - run: npx prisma generate

      - run: npm run test:e2e
        env:
          JWT_SECRET: testing-secret
          DATABASE_URL: "postgresql://docker:docker@localhost:5434/gympassapp?schema=public"
